version: "3.9"

services:
  db:
    image: postgres:16
    container_name: kanbanpro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kanbanpro
      POSTGRES_USER: kanbanuser
      POSTGRES_PASSWORD: kanbanpass
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: