spring:
  application:
    name: kanbanpro
  datasource:
    url: jdbc:postgresql://localhost:5433/kanbanpro
    username: kanbanuser
    password: kanbanpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect